### ISSUE TITLE
Feature : Improvising Navbar UI 

### ISSUE THREAD

**Issue by CODER-Rxj11** [Mansi168/EmoWell#68] opened 2024-05-12 12:40 UTC
#### Optimize design for smooth navigation and accessibility. Focus areas:

- Design Consistency: Ensure uniformity in color scheme, typography, and spacing.

- Responsive Design: Make Navbar adaptable across devices and screen sizes.

- Intuitive Navigation: Improve organization of links for easier user navigation.

- Visual Enhancements: Add engaging visual elements without sacrificing usability.

![devcation vercel app_ (2)](https://github.com/Mansi168/EmoWell/assets/92161985/a9546856-9089-4302-8209-dedf73f23d3c)

**Comment by yashmandi** [comment] 2024-05-12 14:43
Hi @Mansi168 , I can make the navbar look better and attractive, which will suit the overall website. I would like to work on this task, request you to assign this task to me ;)

**Comment by Mansi168** [comment] 2024-05-12 16:31
@CODER-Rxj11 you may start working!

**Comment by Amitooo1** [comment] 2024-05-12 18:05
Hey @Mansi168 as the assigned person is not responding, can i give this issue a try?
and one more thing could you please add a relevant level as per GSSOC as level1/level2/level3

**Comment by CODER-Rxj11** [comment] 2024-05-12 18:28
> @CODER-Rxj11 you may start working!

Thank you for assigning me this issue.

**Comment by sahithinandikula** [comment] 2024-05-14 10:57
@Mansi168 I have noticed that this issue is already assigned, I heard that an issue can be assigned to multiple persons . I am interested in working on it . Could you consider my request and assign it?

**Comment by everly-gif** [comment] 2024-06-07 17:41
@CODER-Rxj11 we have not received any update. Assigning the issue to next interested contributor. @yashmandi issue is yours. Please confirm your availability to work on this issue.

**Comment by yashmandi** [comment] 2024-06-07 17:45
> @CODER-Rxj11 we have not received any update. Assigning the issue to next interested contributor. @yashmandi issue is yours. Please confirm your availability to work on this issue.

hi, sorry but i won't be working on this issue anymore, you can assign this to other contributors.

**Comment by everly-gif** [comment] 2024-06-07 17:52
> > @CODER-Rxj11 we have not received any update. Assigning the issue to next interested contributor. @yashmandi issue is yours. Please confirm your availability to work on this issue.
> 
> hi, sorry but i won't be working on this issue anymore, you can assign this to other contributors.

thanks for this, @Amitooo1 the issue is yours, likewise please confirm your availability to work on this issue. Thanks

**Comment by Amitooo1** [comment] 2024-06-07 18:02
Okay I'll start working on this and give updates by tomorrow

**Comment by everly-gif** [comment] 2024-06-17 07:29
closing, as PR merged

**Closed by everly-gif** 2024-06-17 07:29 UTC
Labels: enhancement, good first issue, gssoc, level2
