### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by Pranjalll01** [Mansi168/EmoWell#36] opened 2024-05-10 18:59 UTC
Hey @Mansi168 
Pranjal Kushwaha here , Contributor@GSSoc'24
repo currently lacks a CODE_OF_CONDUCT.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CODE_OF_CONDUCT.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

could ypu please assign this to me ?

**Comment by Mansi168** [comment] 2024-05-11 05:57
ok, please go ahead!

**Comment by Satyaas1117** [comment] 2024-05-13 10:22
There's no activity since 48hrs, can you please assign it to me?

**Comment by n14rishitha** [comment] 2024-05-19 16:41
Hi @Mansi168 
the code of conduct takes effect (on issues and pull requests, or community activities like events?). Adopting, and enforcing, a code of conduct can help create a positive social atmosphere for your community. I would like to work on this issue . so please assign this task to me.

**Comment by everly-gif** [comment] 2024-06-07 17:22
Hi @Pranjalll01  , there has been no activity on this issue for a long time. Reassigning this issue to the next interested contributor. @Satyaas1117  the issue is yours, Please confirm your availability to work on this issue ASAP, possibly by tomorrow, thanks !

**Comment by everly-gif** [comment] 2024-06-26 18:04
@n14rishitha will you like to take this issue?

**Comment by n14rishitha** [comment] 2024-06-28 07:26
> @n14rishitha will you like to take this issue? Please reply by EOD, post will close this issue.

Yes mam
I'll take up this issue

**Comment by everly-gif** [comment] 2024-06-29 17:32
Assigned to you @n14rishitha, please take over

**Closed** 2024-07-13 11:30 UTC
Labels: documentation, help wanted, gssoc, level1
